### ISSUE TITLE
MarginNote Pro 40% discount

### ISSUE THREAD

**Issue by zitudu** [wowlusitong/awesome-education#5]
国人开发的 PDF/EPUD 记录笔记、翻译、导出学习卡片的学习软件

中文页面：https://marginnote.com/marginnote-store/?lang=zh-hans
英文页面：https://marginnote.com/marginnote-store/

edu 邮箱申请优惠码，目前似乎只有 Mac 上的 Pro 版有 6 折

**Comment by wowlusitong** [comment]
@zitudu 已增加，感谢贡献🎉🎉。可以直接提PR。
